logging:
#  config: classpath:logback-spring.xml
  config: classpath:log4j2-spring.xml
# logging.file 和 logging.path 不能同时使用 http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#boot-features-logging-file-output
#  path: /var/log/df-web/
#  file: web-app.log
  file: /var/log/df-web/web-app.log
#  path: /var/log/df-web/web-app.log
  level:
#    root: info
#  org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: INFO
    com.df.dao: debug


security:
#  headers:
#    frame: false
#  user:
#    password: 123456
  cas:
    service: http://df.qbao.com/login/cas
    casServerUrlPrefix: http://passport.qbao.com/cas
    loginUrl: http://passport.qbao.com/cas/qianbaoLogin
    authenticateAllArtifacts: false
# test的路径不添加权限限制为了测试@WebMvcTest功能
  ignored: /test/**

#spring:
#  datasource:
#            type: com.alibaba.druid.pool.DruidDataSource
#            druid:
#              initialSize: 1
#              minIdle: 1
#              maxActive: 20
#              maxWait: 60000
#              timeBetweenEvictionRunsMillis: 60000
#              minEvictableIdleTimeMillis: 300000
#              validationQuery: SELECT 'x'
#              testWhileIdle: true
#              testOnBorrow: false
#              testOnReturn: false
#              poolPreparedStatements: false
#              maxPoolPreparedStatementPerConnectionSize: 20
#              filters: stat

mybatis:
    type-aliases-package: com.df.domain
#    type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

server:
    port: 80

#指定触发器文件没看到效果
#spring:
#  devtools:
#    restart:
#      trigger-file: "C:/Users/Administrator/.reloadtrigger"

#指定外部banner没看到效果
#banner:
#  image:
#    location: 'D:/image/banner-20160215.jpg'

#spring:
#    main:
#        banner-mode: "off"

#作用不明
#spring:
#  application:
#    admin:
#      enabled: true

#测试属性设置优先级：command-line-argument > System-Variable > environment-variable > Application property files
name: Spring

# https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/#production-ready-customizing-endpoints
endpoints:
  beans:
#  修改beans默认endpoint id
    id: springbeans
#  不需要授权
    sensitive: false
  shutdown:
#  通过post请求停止服务
    enabled: true

spring:
  profiles:
      active: ubuntu

  datasource:
      multiple:
            type: com.alibaba.druid.pool.DruidDataSource
            initialSize: 1
            minIdle: 1
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat
            enabled: true
            defaultDataSourcesName: df
            multipleDataSourcesNames: user01,user02,user03
            df:
              url: jdbc:mysql://localhost:3306/df?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345
            user01:
              url: jdbc:mysql://localhost:3306/df_user01?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345
            user02:
              url: jdbc:mysql://localhost:3306/df_user02?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345
            user03:
              url: jdbc:mysql://localhost:3306/df_user03?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: xuchengdong@qbao.com
    password: '********'
# 内置属性参考 com.sun.mail.smtp.SMTPTransport.SMTPTransport
    properties:
      mail:
        debug: true
        smtp:
         connectiontimeout: 5000
         timeout: 3000
         writetimeout: 5000
         ssl:
          enable: true
  cache:
# 限定可用的缓存
    cache-names: user,role
# 某些场景下禁用缓存
#    type: none


---
server:
    port: 8080
spring:
  profiles: centos
  redis:
    pool:
      max-wait: 1000
    sentinel:
      master: socialcp
      nodes: 192.168.131.13:26379,192.168.131.13:26380,192.168.131.13:26381
  activemq:
    broker-url: tcp://192.168.131.221:61616
#    user: admin
#    password: secret
    pool:
      enabled: true
      max-connections: 50
  rabbitmq:
    host: 192.168.131.221
    port: 5672
    username: xucd
    password: xucd


---
server:
    port: 8080
spring:
  profiles: ubuntu
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 50
  rabbitmq:
    host: localhost
    port: 5672
    username: xucd
    password: xucd
