logging:
#  config: classpath:logback.xml
  config: classpath:log4j2.xml
#  path: /var/log/spring-devkit/ 指定path不起作用 需要直接指定file完整路径
  file: /var/log/df-web/web-app.log
#  level:
#    root: info

#spring:
#  datasource:
#            type: com.alibaba.druid.pool.DruidDataSource
#            druid:
#              initialSize: 1
#              minIdle: 1
#              maxActive: 20
#              maxWait: 60000
#              timeBetweenEvictionRunsMillis: 60000
#              minEvictableIdleTimeMillis: 300000
#              validationQuery: SELECT 'x'
#              testWhileIdle: true
#              testOnBorrow: false
#              testOnReturn: false
#              poolPreparedStatements: false
#              maxPoolPreparedStatementPerConnectionSize: 20
#              filters: stat

mybatis:
    type-aliases-package: com.df.domain
#    type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

server:
    port: 9080

#指定触发器文件没看到效果
#spring:
#  devtools:
#    restart:
#      trigger-file: "C:/Users/Administrator/.reloadtrigger"

#指定外部banner没看到效果
#banner:
#  image:
#    location: 'D:/image/banner-20160215.jpg'

#spring:
#    main:
#        banner-mode: "off"
---
spring:
  profiles: development
  datasource:
          multiple:
            type: com.alibaba.druid.pool.DruidDataSource
            initialSize: 1
            minIdle: 1
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat
            enabled: true
            defaultDataSourcesName: df
            multipleDataSourcesNames: user01,user02,user03
            df:
                url: jdbc:mysql://localhost:3306/df?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
                username: root
                password: 12345
            user01:
              url: jdbc:mysql://localhost:3306/df_user01?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345
            user02:
              url: jdbc:mysql://localhost:3306/df_user02?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345
            user03:
              url: jdbc:mysql://localhost:3306/df_user03?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
              username: root
              password: 12345

---
spring:
  profiles: production
  datasource:
          druid:
            url: jdbc:mysql://192.168.81.49:3306/df?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false
            username: root
            password: 12345