spring:
  datasource:
    url: jdbc:mysql://192.168.131.27:3306/userdist?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: uc2017